services:
  db:
    image: mysql
    restart: no
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: spliticket
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: spliticket