services:
  db:
    image: mysql
    restart: no
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: spliticket
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: spliticket
    networks:
      - spliticket
  api:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: spliticket
      DB_USERNAME: spliticket
      DB_PASSWORD: password
    networks:
      - spliticket

networks:
  spliticket:
